# Generated by Django 3.1.3 on 2020-11-28 05:21

import FSApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSApp', '0002_auto_20201127_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=254, validators=[FSApp.models.validate_email]),
        ),
    ]
